### ISSUE TITLE
Exception when loading site with JavaScript

### ISSUE THREAD

**Issue by LeMoussel** [AngleSharp/AngleSharp.Scripting#20]
Whne loading site http://www.eco2energie.biz/ I got this exception:
````
   à AngleSharp.Scripting.JavaScript.DomFunctionInstance.Call(JsValue thisObject, JsValue[] arguments) dans c:\Users\lemoussel\AngleSharp\AngleSharp.Scripting\AngleSharp.Scripting.JavaScript\DomFunctionInstance.cs:ligne 38
   à Jint.Runtime.ExpressionInterpreter.EvaluateCallExpression(CallExpression callExpression)
   à Jint.Engine.EvaluateExpression(Expression expression)
   à Jint.Runtime.ExpressionInterpreter.EvaluateExpression(Expression expression)
   à Jint.Runtime.ExpressionInterpreter.EvaluateAssignmentExpression(AssignmentExpression assignmentExpression)
   à Jint.Engine.EvaluateExpression(Expression expression)
   à Jint.Runtime.StatementInterpreter.ExecuteExpressionStatement(ExpressionStatement expressionStatement)
   à Jint.Engine.ExecuteStatement(Statement statement)
   à Jint.Runtime.StatementInterpreter.ExecuteStatement(Statement statement)
   à Jint.Runtime.StatementInterpreter.ExecuteStatementList(IEnumerable`1 statementList)
````

````C#
            IConfiguration config = new Configuration().WithDefaultLoader().WithCss().WithCookies().WithJavaScript();
            IBrowsingContext context = BrowsingContext.New(config);
            IDocument document = await context.OpenAsync("http://www.eco2energie.biz/");
            await Task.WhenAll(document.Requests);
````

**Comment by FlorianRappl** [comment]
I'll look into it!

**Comment by rikku47** [comment]
Hello,

I get an Exeption too

The Message:

System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.TypeLoadException: Der Typ "AngleSharp.Network.MimeTypes" in der Assembly "AngleSharp, Version=0.9.4.42449, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea" konnte nicht geladen werden.
   bei AngleSharp.Scripting.JavaScript.ScriptingService.GetEngine(String mimeType)
   bei AngleSharp.Dom.Html.HtmlScriptElement.get_Engine()
   bei AngleSharp.Dom.Html.HtmlScriptElement.Prepare(Document document)
   bei AngleSharp.Parser.Html.HtmlDomBuilder.HandleScript(HtmlScriptElement script)
   bei AngleSharp.Parser.Html.HtmlDomBuilder.Text(HtmlToken token)
   bei AngleSharp.Parser.Html.HtmlDomBuilder.Home(HtmlToken token)
   bei AngleSharp.Parser.Html.HtmlDomBuilder.Consume(HtmlToken token)
   bei AngleSharp.Parser.Html.HtmlDomBuilder.<ParseAsync>d__0.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei AngleSharp.Dom.Html.HtmlDocument.<LoadAsync>d__1f.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei AngleSharp.BrowsingContextExtensions.<OpenAsync>d__3.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei Console_C_Sharp.Program.<Connect>d__1.MoveNext() in C:\Users\...\documents\visual studio 2015\Projects\Console_C_Sharp\Console_C_Sharp\Program.cs:Zeile 63.
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   bei System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bei System.Threading.Tasks.Task.Wait()
   bei Console_C_Sharp.Program.Main(String[] args) in C:\Users\...\documents\visual studio 2015\Projects\Console_C_Sharp\Console_C_Sharp\Program.cs:Zeile 15.
---> (Interne Ausnahme #0) System.TypeLoadException: Der Typ "AngleSharp.Network.MimeTypes" in der Assembly "AngleSharp, Version=0.9.4.42449, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea" konnte nicht geladen werden.
   bei AngleSharp.Scripting.JavaScript.ScriptingService.GetEngine(String mimeType)
   bei AngleSharp.Dom.Html.HtmlScriptElement.get_Engine()
   bei AngleSharp.Dom.Html.HtmlScriptElement.Prepare(Document document)
   bei AngleSharp.Parser.Html.HtmlDomBuilder.HandleScript(HtmlScriptElement script)
   bei AngleSharp.Parser.Html.HtmlDomBuilder.Text(HtmlToken token)
   bei AngleSharp.Parser.Html.HtmlDomBuilder.Home(HtmlToken token)
   bei AngleSharp.Parser.Html.HtmlDomBuilder.Consume(HtmlToken token)
   bei AngleSharp.Parser.Html.HtmlDomBuilder.<ParseAsync>d__0.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei AngleSharp.Dom.Html.HtmlDocument.<LoadAsync>d__1f.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei AngleSharp.BrowsingContextExtensions.<OpenAsync>d__3.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei Console_C_Sharp.Program.<Connect>d__1.MoveNext() in C:\Users\...\documents\visual studio 2015\Projects\Console_C_Sharp\Console_C_Sharp\Program.cs:Zeile 63.<---

Here my C# code so far:

             var configuration = Configuration.Default.WithDefaultLoader().WithJavaScript().WithCookies();

            //var WebsiteUrl = "http://www.tremorgames.com/login.html";
            var WebsiteUrl = "http://www.gamestar.de/index.cfm?pid=103&op=10";
            //var WebsiteUrl = "http://www.boerse.de/aktien/Aluminium/kursliste";

            var context = BrowsingContext.New(configuration);
            await context.OpenAsync(WebsiteUrl);

It crash after I let it debug/one step ahead by: await context.OpenAsync(WebsiteUrl);

When I remove .WithJavaScript() at:

var configuration = Configuration.Default.WithDefaultLoader().WithJavaScript().WithCookies();

it works.

Please help and thank you.

I hope its ok, that it is in german.

best regards

Freundliche Grüße

**Comment by FlorianRappl** [comment]
The JavaScript is causing the issue (probably / usually a (currently) unsupported feature, e.g., using strings as functions or relying on some DOM interface that is just not implemented).

**Comment by useruser1** [comment]
I wrote about this problem early, Florian

**Comment by FlorianRappl** [comment]
I don't know what you mean. And one of the questions I have to ask you is: If you care about AngleSharp, why don't you star it? You know that stars are the currency on GitHub. If repos are not starred then they are abandoned.
