### ISSUE TITLE
Execute <script> tags added from javascript

### ISSUE THREAD

**Issue by EtienneCoumont** [AngleSharp/AngleSharp.Scripting#24]
I'm trying to render some html page that contains the following script : 
```
<script>
    var d = document, s = d.createElement('script');
    s.src = 'dynamicload.js';
    (d.head || d.body).appendChild(s);
</script>
```
The resulting html is ok :
`... <head><script src="dynamicload.js"></script></head> ...`
But dynamicload.js does not seem to be loaded.

When I load directly the html `<script src="dynamicload.js"></script>`, everything works fine.

Am I missing something ?

**Comment by FlorianRappl** [comment]
I think this is a potential problem in AngleSharp (I am not sure yet if this is already noticed and fixed in the upcoming version -- I will check this). The evaluation takes place too early and is therefore performed with the `src` attribute, i.e., nothing will be downloaded and executed.

**Comment by FlorianRappl** [comment]
I marked it as a bug here, but this is an AngleSharp issue. I will check before releasing the latest version there.

Marked for v0.4 since v0.4 will depend on this latest version.

**Comment by FlorianRappl** [comment]
I'll close it here and open it in AngleSharp itself. Otherwise, it is overlooked too easily.
