### ISSUE TITLE
How to access the DOM from javascript?

### ISSUE THREAD

**Issue by wataabirs** [AngleSharp/AngleSharp.Scripting#29]
Hi,

I try to use the following code to access a DOM object inside the HTML:

```cs
var config = Configuration.Default.WithJavaScript().WithCss();
var parser = new HtmlParser(config);
// sample html
var source = @"<!doctype html><html><body><div id='test'>content</div></body>";
var document = parser.Parse(source);
var jsService = config.Services.OfType<JavaScriptProvider>().FirstOrDefault(x => x.Engine.Type == "text/javascript");
var jintEngine = jsService.Engine.GetOrCreateJint(document);
// trying to modify the context, but I don't know how to specify the correct thisBinding
jintEngine.EnterExecutionContext(jintEngine.GlobalEnvironment, jintEngine.GlobalEnvironment, ???);

// try to extract the contents of the div with JS
var result = jintEngine.Execute("document.querySelectorAll('#test').innerHTML").GetCompletionValue();

jintEngine.LeaveExecutionContext();
Console.WriteLine(result);
```

Some remarks:
- I'm not allowed to modify the html content in the 'source' variable
- I'm not sure if modifying the execution context is the correct way

The problem:
When I run this code (without modifying the execution environment) I get a JavascriptException saying that the 'document' is undefined. I've tried to modify the execution environment, but I have no idea what the correct value for the thisBinding parameter is in the EnterExecutionContext function. How can I set it to the window or the document?

**Comment by FlorianRappl** [comment]
I think a little bit too much is done here. Is there a specific reason for modifying the context? Why don't you want to run from the `IWindow` context?

See: https://github.com/AngleSharp/AngleSharp.Samples/blob/master/AngleSharp.Samples.App/ViewModels/ReplViewModel.cs for another example how to run JS against the DOM (here in a REPL).

If you really need this, then just do it like the scripting library does it:

```cs
_engine.EnterExecutionContext(Lexicals, Variables, _window);
_engine.Execute(source);
_engine.LeaveExecutionContext();
```

`_window` can be used via `document.DefaultView`. Hope this helps!

**Comment by wataabirs** [comment]
Hello,

What do you mean by running from the IWindow context? (sorry I'm new to the library)
I've checked the AngleSharp.Samples project, opened a web page and started playing with the REPL in the 'Console' tab. The 'window' and 'document' objects are undefined there also.

Regarding the execution context switch: the type of the 3rd parameter in the EnterExecutionContext function is `JsValue`. The `document.DefaultView` property has a type of `IWindow`, so when I used it I get a compiler error (cannot convert from IWindow to JsValue), and I don't know how to convert that `IWindow` instance to a proper `JsValue`.

**Comment by FlorianRappl** [comment]
I don't know why this is not working in the samples project (maybe as I've seen from your Fiddle you using the wrong combination - both, AngleSharp and AngleSharp.Scripting.JavaScript should be taken with their latest versions; here you just used AngleSharp.Scripting.JavaScript with implicitly used an older version of AngleSharp).

Either way I think there is some connection to #19. I've added an extension method and the unit tests pass.

Essentially, it allows you to do:

```cs
var config = Configuration.Default.WithJavaScript().WithCss();
var parser = new HtmlParser(config);
// sample html
var source = @"<!doctype html><html><body><div id='test'>content</div></body>";
var document = parser.Parse(source);
var result = document.ExecuteScript("document.querySelectorAll('#test').innerHTML");
Console.WriteLine(result);
```

All the rest from above is not required.

**Comment by wataabirs** [comment]
It works perfectly, many thanks :).
There is just a small typo in the `document.ExecuteScript` line: the js expression should be `document.querySelectorAll('#test')[0].innerHTML`

**Comment by FlorianRappl** [comment]
Yes, edited. I just copied the one from above (your initial post) to illustrate the idea / savings in LOC.
