### ISSUE TITLE
window.location.href processing

### ISSUE THREAD

**Issue by DruSatori** [AngleSharp/AngleSharp.Scripting#32]
Pretty sure I'm just missing something obvious, but I am failing to see how this works, and as far as I can tell it does not in the Sample project.

Loading a first web page ( as an example in the test case below ), http://www.druware.com/unittests/window.location.href-set.html 

Assuming that page contains a script that changes the location.href which should trigger the window to load a new document with a new document. I see that the script is processed and loads the new document in the script context, so with the internal await on the OpenAsync() in Document.cs:1527, 

```
                await _context.OpenAsync(request, CancellationToken.None);
```

it all happens synchronous. I *think* there is in issue in that the above code doesn't update the IHtmlDocument, so that even though the Location is changed, and the IHtmlDocument show the new address, the content of the parsed results remain those of the original document.

I tried to get to the newly loaded document from the Context.Active, but that too, is the original document data.

**Comment by DruSatori** [comment]
Issue appears to effect location.assign(); as well.

**Comment by FlorianRappl** [comment]
A MWE to reproduce your issue would be helpful.

**Comment by DruSatori** [comment]
I'll create something in the morning, but using the Demo app navigate to any url, goto the console and execute:

``` window.location.href = "http://www.google.com"; ```

or 

``` window.location.assign("http://www.google.com"); ```

either demonstrates the issue. 

Sorry about the missing MWE, spent the afternoon installing a windows VM and VS.NET so I could work with your demos and unit tests rather than trying to fight through things in Xamarin or VS for Mac, neither of which support the MS Test tools.

**Comment by FlorianRappl** [comment]
Works for me. Simple MWE to reproduce:

```cs
var config = Configuration.Default.WithJavaScript().WithDefaultLoader();
var context = BrowsingContext.New(config);
await context.OpenAsync(res => res.Content(@"
<title>I am the homepage</title>
<script>window.location.href = 'http://www.google.com';</script>
"));

for (var i = 0; i < 10; i++)
{
    Console.WriteLine(context.Active.Title);
    await Task.Delay(1000);
}
```

Output for me:

```plain
I am the homepage
Google
Google
Google
Google
Google
Google
Google
Google
Google
```

Important: Everything's asynchronous (hence the Google homepage is not loaded directly when we print the first time, but here as the second (may also be third, fourth or fifth time). I intentionally printed every second that one can see the "progress".

**Comment by DruSatori** [comment]
Alter that to load the document first, and then execute the script after the document is loaded.  The Document content remains unchanged. In addition, there is no notification, or process for seeing when the document content has indeed changed.

```
var config = Configuration.Default.WithJavaScript().WithDefaultLoader();
var context = BrowsingContext.New(config);
await context.OpenAsync(res => res.Content(@"
<title>I am the homepage</title>
"));

context.Active.ExecuteScript("window.location.href = 'http://www.google.com';");

for (var i = 0; i < 10; i++)
{
    Console.WriteLine(context.Active.Title);
    await Task.Delay(1000);
}
```


The above is untested, as I am not near a machine that I can test it on right now.

**Comment by FlorianRappl** [comment]
The code above still works (same output as shown earlier).

**Comment by DruSatori** [comment]
which circles back to my original statement about missing something simple, sitting in a wait loop until the content changes.

That said, would it make sense to set up some sort of notification or event to handle when the document changes via script?

**Comment by DruSatori** [comment]
In the case of the mutation observer,  that really wouldn't apply in the case of changing the window.location would it? since it creates a new document.  Is there an equivalent on the context or window that could be monitored for when the document changes?

**Comment by FlorianRappl** [comment]
Please read my answer carefully: The mutation observer is only for content changes. The `window` is replaced as well; there is a 1-1 relationship (as specified by the W3C) between the window and the document.

You can roll your own version of the context to support change notifications (only implement `IBrowsingContext`). The version provided by the core is only rudimentary. The `AngleSharp.Browser` extension (which will come eventually) will contain a much more complete version (however, that one would be overkill for the core).

Monitoring can (of course) only occur from C# as JavaScript is running within the document that is destroyed / replaced.

**Comment by DruSatori** [comment]
Last note on this.  I've got a working solution now, so thanks, I'll write it up in a bit, still need to clean up all of the notes I've made through this.

I should note that in getting it working I think I've identified a potential bug.  Figured I'd post it here and let you decide if you want it in a separate thread or not. 

```
			var config = Configuration.Default.WithJavaScript().WithDefaultLoader();
			var context = BrowsingContext.New(config);
			await context.OpenAsync(res => res.Content(@"
<title>I am the homepage</title>
<script>window.location.assign('http://www.google.com');</script>
"));

			for (var i = 0; i < 10; i++)
			{
				Console.WriteLine(context.Active.Title);
				await Task.Delay(1000);
			}
```

Never reloads, though using the href assignment does.

**Comment by FlorianRappl** [comment]
Yeah, this is a bug as the assign is not triggering the change event. But the bug should be assigned to the core; it has nothing to do with the JavaScript integration.

Can you file the bug in the core repository? Thanks!
