### ISSUE TITLE
State of CSharp engine?

### ISSUE THREAD

**Issue by georgiosd** [AngleSharp/AngleSharp.Scripting#38]
I was impressed with the `ToDynamic()` functionality!

But you mention it's unstable/got stuff missing - can you please be more specific?
What do you think is missing/wouldn't work?

**Comment by FlorianRappl** [comment]
Yeah, there are:

- some TODOs in the code (e.g., problems with indexers)
- adding event handlers should be possible
- need specializations depending on the exact node type

These are just the ones from the top of my head. Of course, there could be others. Some of them are just "nice to have", while others are definitely required for this lib / extension to be useful.

**Comment by georgiosd** [comment]
I see, thanks!
