### ISSUE TITLE
Accessing Document.ReadyState in JavaScript exposes enum value instead of string

### ISSUE THREAD

**Issue by Sebbs128** [AngleSharp/AngleSharp.Scripting#86]
# Bug Report

## Prerequisites

- [X] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [X] Are you running the latest version of AngleSharp?
- [X] Did you check the FAQs to see if that helps you?
- [X] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [X] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description

Creating this as the AngleSharp.Js counterpart to https://github.com/AngleSharp/AngleSharp/issues/1109

When JavaScript in a HTML document reads the `document.readyState` property, the value returned is a digit (the underlying value of the `DocumentReadyState` enum) instead of the expected string (such as `"loading"` or `"complete"`).

## Steps to Reproduce
Reproduction using Top Level Statements

```csharp
using AngleSharp;
using AngleSharp.Js;

string html = """
            <html>
                <head>
                    <script type="text/javascript">
                        document.onreadystatechange = function() {
                            console.log("Document OnReadyStateChange fired");
                            console.log(document.readyState);
                            
                            if (document.readyState == "complete")
                                console.log("document state is complete");
                                
                            if (document.readyState == 1)
                                console.log("document state is 1");
                        };
                    </script>
                </head>
            </html>
            """;

var browserContext = BrowsingContext.New(Configuration.Default
    .WithJs()
    .WithConsoleLogger(ctx => new ConsoleLogger())
    .WithEventLoop());

var doc = await browserContext.OpenAsync(m => m.Content(html)).WhenStable();

class ConsoleLogger : IConsoleLogger
{
    public void Log(object[] values)
    {
        var elements = values.Select(m => (m ?? String.Empty).ToString());
        var content = String.Join(", ", elements);
        Console.WriteLine(content);
    }
}
```

Output will be
```
Document OnReadyStateChange fired
1
document state is 1
Document OnReadyStateChange fired
2
```

**Expected behavior:**

`document.readyState` call in JavaScript should return a string of either `"loading"`, `"interactive"`, or `"complete"`.

For the reproduction above, the expected output should be
```
Document OnReadyStateChange fired
interactive
Document OnReadyStateChange fired
complete
document state is complete
```

**Actual behavior:**

`document.readyState` call in JavaScript is returning the underlying enum value (ie. `0`, `1`, or `2`)

**Environment details:**
OS: Win11x64
Runtime: .NET 7.0.201

## Possible Solution

When converting an enum value to `JsValue`, check if it has an official name (via `DomNameAttribute`), and use that value instead.

**Comment by Sebbs128** [comment]
I'm currently working on this in a forked branch, just don't seem to be able to assign the issue to myself.

I have the code changes in place, just currently working through the tests (12 currently fail due to the changes)

**Comment by Sebbs128** [comment]
Test failures are due to enums like `AngleSharp.Dom.NodeType` and `AngleSharp.Js.Dom.RequesterState` needing to be the enum value. Instead, opting for just addressing `DocumentReadyState` and leaving addressing other enums as they're brought to attention.

**Comment by FlorianRappl** [comment]
Landed in pre-release.
