### ISSUE TITLE
Chrome alternative

### ISSUE THREAD

**Issue by AlexanderStromer** [AngleSharp/AngleSharp.Scripting#88]
Thank you for your effort and enthusiasm in making AngleSharp and evolving its architecture to what it is today!

I am looking for a good and integer alternative to the full blown headless versions of Chromium etc, which size-wise are unfortunately way to overblown (each release consumes ~150MB on disk). However, I am struggling to get AngleSharp running for my scenario. My first hurdle was that file references css/script resources were not automatically fetched from the server (I had to 
`.WithDefaultLoader(new LoaderOptions { IsResourceLoadingEnabled = true })`
which isn't explained anywhere. In fact, I would have expected that references are automatically fetched.

In addition, all fetched scripts files (~ 10 medium sized minified JS files) incl ASP.NET WebForms-based [ScriptManager-functionality](https://learn.microsoft.com/en-us/dotnet/api/system.web.ui.scriptmanager) are not boot-loaded and therefore the page does not produce the desired outcome (some DOM manipulations).

I have 2 questions:

1. Is there any logging/tracing functionality, which can track the inner working of AngleSharp / AngleSharp.js? Tracing would let me diagnose where the issue for my concrete scenario is.
3. Do you think it is viable to use AngleSharp for above-mentioned complex scenario?

Sidenote: I was not able to reach you on twitter, as you cannot be contacted there directly (some setting on your end I believe)

**Comment by FlorianRappl** [comment]
Unfortunately AngleSharp.Js is outdated. As there are financial backers for this particular project I had to focus my time on other projects that have direct supports (and therefore seem to be more relevant to people).

The documentation of AngleSharp itself is open-source (as the project is). Generally, people seemed to be quite fond of it (it was the one thing blocking a 1.0 release and people told me explicitly that the docs are good enough and I should finally ship it - so my democratic vote docs are good and if something crucial is indeed missing then just make a PR with the addition).

To your questions:

1. No
2. Not sure what you want to use it for - but if you are looking for the full Chrome functionality; no (again AngleSharp.Js is unmaintained right now and therefore you'd not have a JS engine which I guess is what you are looking for)

Hope that helps!
