### ISSUE TITLE
Pass values back and forth between Javascript & C#

### ISSUE THREAD

**Issue by GuerrillaCoder** [AngleSharp/AngleSharp.Scripting#9]
Hi,

I am looking at replacing the web browser control in my C# winforms app with AngleSharp.

Is it possible to pass values back and forth from C# and JavaScript methods? 

With the web browser control the way I currently do it is:

JavaScript to C#:
var return = window.external.MyCSharpFunc(myValue);

C# to JavaScript:
var return = WebBrowser.Document.InvokeScript("MyJSFunc", new object[] { myValue });

How would I go about doing this with anglesharp and jint?  Are there any examples anywhere?

**Comment by FlorianRappl** [comment]
Yes, this would have been possible formerly much more easily, but I am in the process of restructuring the JS library anyway (and bringing it forward from experimental stage to being actually useful).

I am currently extending it with everything you need to do that.

Just to give you two examples of what will be released (tomorrow):

Reading a (global) variable from C#:

```csharp
var service = new ScriptingService();
var cfg = Configuration.Default.With(service);
var html = "<!doctype html><script>var foo = 'test';</script>";
var document = await BrowsingContext.New(cfg).OpenAsync(m => m.Content(html));
var foo = service.Engine.GetJint(document).GetValue("foo");
Assert.AreEqual("test", foo.AsString());
```

Running a function (def. in JS) from C#:

```csharp
var service = new ScriptingService();
var cfg = Configuration.Default.With(service);
var html = "<!doctype html><script>function square(x) { return x * x; }</script>";
var document = await BrowsingContext.New(cfg).OpenAsync(m => m.Content(html));
var square = service.Engine.GetJint(document).GetValue("square");
var result = square.Invoke(4);
Assert.AreEqual(16.0, result.AsNumber());
```

The access of C# functions from JS will be possible as well - I am thinking right now about a good mechanism that also allows injecting more complicated structures easily.

**Comment by FlorianRappl** [comment]
This topic is also related to #3.

**Comment by GuerrillaCoder** [comment]
Excellent, I look forward to the release :)

**Comment by FlorianRappl** [comment]
As far as the other way is concerned I guess the following solution will be sufficient:

```csharp
var service = new ScriptingService();
var cfg = Configuration.Default.With(service);
var storedValue = 0.0;
service.Engine.External["square"] = new Action<Double>(x => storedValue = x);
var html = "<!doctype html><script>square(4 * 4);</script>";
var document = await BrowsingContext.New(cfg).OpenAsync(m => m.Content(html));
Assert.AreEqual(16.0, storedValue);
```

This can be much more complex, e.g.:

```csharp
var service = new ScriptingService();
var cfg = Configuration.Default.With(service);
service.Engine.External["person"] = new Person { Age = 20, Name = "Foobar" };
var html = "<!doctype html><script>var str = person.Name + ' is ' + person.Age + ' years old';</script>";
var document = await BrowsingContext.New(cfg).OpenAsync(m => m.Content(html));
var str = service.Engine.GetJint(document).GetValue("str");
Assert.AreEqual("Foobar is 20 years old", str.AsString());
```

where I used a custom class

```csharp

class Person
{
    public String Name
    {
        get;
        set;
    }

    public Int32 Age
    {
        get;
        set;
    }
}
```

Note - I did not do much here (only provided the dictionary, which will be used for assignments once an engine is initialized internally). The nice interaction with .NET comes already from Jint.

**Comment by FlorianRappl** [comment]
This is all working very nicely now.
